android {
    namespace "com.example.smflasher_nota" // ganti sesuai package kamu
    compileSdkVersion 34
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    defaultConfig {
        applicationId "com.example.smflasher_nota"
        minSdkVersion 21
        targetSdkVersion 34 // INI PENTING
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
